services:
    data-helper:
        volumes:
            -   postgres:/container-data/postgres
    database:
        build: ./compose-recipes/postgres
        container_name: ${NAMESPACE}-database-postgres
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 1G
        environment:
            -   POSTGRES_DB=${DATABASE_NAME}
            -   POSTGRES_USER=liferay
            -   POSTGRES_PASSWORD=password
        healthcheck:
            interval: 5s
            retries: 50
            start_period: 30s
            test: pg_isready -U liferay -d ${DATABASE_NAME} && grep 'STARTING_UP' /startup_log.txt
            timeout: 5s
        ports:
            -   "5433:5432"
        shm_size: 128mb
        volumes:
            -   dumps:/docker-entrypoint-initdb.d
            -   postgres:/var/lib/postgresql/data
volumes:
    postgres: