services:
    database:
        image: postgres:16.3
        container_name: "${NAMESPACE}-database-postgres"
        shm_size: 128mb
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=liferay
            - POSTGRES_PASSWORD=password
        healthcheck:
            interval: 5s
            retries: 50
            start_period: 30s
            test: "pg_isready -U liferay -d ${DATABASE_NAME}"
            timeout: 5s
        ports:
            - "5433:5432"
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 1G
        volumes:
            -   read_only: true
                source: data-volume
                target: /docker-entrypoint-initdb.d
                type: volume
                volume:
                    subpath: dumps
            -   source: data-volume
                target: /var/lib/postgresql/data
                type: volume
                volume:
                    subpath: container-data/postgres