services:
    data-helper:
        volumes:
            -   elasticsearch:/container-data/elasticsearch
    elasticsearch:
        build: ./compose-recipes/elasticsearch
        container_name: ${NAMESPACE}-elasticsearch
        environment:
            -   ES_JAVA_OPTS=-Xms1g -Xmx1g
            -   cluster.name=LiferayElasticsearchCluster
            -   discovery.type=single-node
            -   http.port=9200
            -   transport.port=9300
            -   xpack.ml.enabled=false
            -   xpack.monitoring.enabled=false
            -   xpack.security.enabled=false
            -   xpack.sql.enabled=false
            -   xpack.watcher.enabled=false
        healthcheck:
            interval: 10s
            retries: 10
            test: curl localhost:9200/_cat/health | grep green
            timeout: 5s
        mem_limit: 4g
        ports:
            -   9200:9200
            -   9300:9300
        volumes:
            -   elasticsearch:/usr/share/elasticsearch/data/
volumes:
    elasticsearch: