services:
    liferay:
        container_name: ${NAMESPACE}-liferay
        healthcheck:
            interval: 5s
            start_period: 5m
            test: "/opt/liferay/health-check.sh"
            timeout: 5m
        image: "${LIFERAY_IMAGE_NAME}"
        ports:
            - "8080:8080"
            - "11311:11311"
            - "8000:8000"
        volumes:
            - source: data-volume
              target: /opt/liferay/data
              type: volume
              volume:
                  subpath: container-data/liferay